# Generated by Django 4.1.3 on 2022-11-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
